version: '2'
services:
  aws-ecs-demo-api:
    cpu_shares: 100
    mem_limit: 134217728
    image: aws-ecs-demo-api:latest
    ports:
      - "5000:5000"
    networks:
      - overlay
  aws-ecs-demo-ui:
    cpu_shares: 100
    mem_limit: 134217728
    image: aws-ecs-demo-ui:latest
    ports:
      - "5001:80"
    networks:
      - overlay
networks:
  overlay: